/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cpp_SayHello */

#ifndef _Included_cpp_SayHello
#define _Included_cpp_SayHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpp_SayHello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cpp_SayHello_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
