/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cpp_ExampleObjects */

#ifndef _Included_cpp_ExampleObjects
#define _Included_cpp_ExampleObjects
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpp_ExampleObjects
 * Method:    createUser
 * Signature: (Ljava/lang/String;D)Lcpp/ExampleObjects/UserData;
 */
JNIEXPORT jobject JNICALL Java_cpp_ExampleObjects_createUser
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     cpp_ExampleObjects
 * Method:    printUserData
 * Signature: (Lcpp/ExampleObjects/UserData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cpp_ExampleObjects_printUserData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
