/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cpp_ExampleParameters */

#ifndef _Included_cpp_ExampleParameters
#define _Included_cpp_ExampleParameters
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpp_ExampleParameters
 * Method:    sumIntegers
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_cpp_ExampleParameters_sumIntegers
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cpp_ExampleParameters
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cpp_ExampleParameters_sayHelloToMe
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
