/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ExampleObjects */

#ifndef _Included_ExampleObjects
#define _Included_ExampleObjects
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ExampleObjects
 * Method:    createUser
 * Signature: (Ljava/lang/String;D)LUserData;
 */
JNIEXPORT jobject JNICALL Java_ExampleObjects_createUser
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     ExampleObjects
 * Method:    printUserData
 * Signature: (LUserData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ExampleObjects_printUserData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
