/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_ExampleObjects */

#ifndef _Included_JNI_ExampleObjects
#define _Included_JNI_ExampleObjects
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_ExampleObjects
 * Method:    createUser
 * Signature: (Ljava/lang/String;D)LJNI/UserData;
 */
JNIEXPORT jobject JNICALL Java_JNI_ExampleObjects_createUser
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     JNI_ExampleObjects
 * Method:    printUserData
 * Signature: (LJNI/UserData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNI_ExampleObjects_printUserData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
