/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_SayHello */

#ifndef _Included_JNI_SayHello
#define _Included_JNI_SayHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_SayHello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNI_SayHello_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
