/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_ExampleParameters */

#ifndef _Included_JNI_ExampleParameters
#define _Included_JNI_ExampleParameters
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_ExampleParameters
 * Method:    sumIntegers
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_JNI_ExampleParameters_sumIntegers
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNI_ExampleParameters
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNI_ExampleParameters_sayHelloToMe
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
