/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SayHello */

#ifndef _Included_SayHello
#define _Included_SayHello
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     SayHello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
  JNIEXPORT jstring JNICALL Java_SayHello_sayHello(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
